project:
  type: manuscript
  render:
    - "!notes.md"

execute:
  freeze: true
  cache: true

manuscript:
  article: index.qmd

format:
  html:
    comments:
      hypothesis: true
  docx: default
  jats: default
  elsevier-pdf:
      keep-tex: true

  # (other formats)
